# .yarnrc.yml
nodeLinker: pnp

# PnP 환경에서 Prisma 호환성 설정
pnpFallbackMode: dependencies-only

packageExtensions:
  "@prisma/client@*":
    dependencies:
      prisma: "*"
    peerDependencies:
      prisma: "*"
