import type {Metadata} from "next";

import "./globals.css";
import {Inter} from "next/font/google";
import QueryProvider from "@/components/providers/query-provider";
import {LoadingProvider} from "@/context/loading-context";
import {GlobalLoadingOverlay} from "@/components/ui/global-loading-overlay";
import { LocationProvider } from "@/context/location-context"; // Import LocationProvider

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={inter.className}
        >
        <LoadingProvider>
            <QueryProvider>
                <LocationProvider> {/* Wrap children with LocationProvider */}
                    {children}
                </LocationProvider>
            </QueryProvider>
            <GlobalLoadingOverlay />
        </LoadingProvider>
        </body>
        </html>
    );
}
